package dev.mars.server.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table MESSAGE.
 */
public class Message implements Serializable {

    private Long id;
    private String title;
    private String summary;
    private String content;
    private Integer type;
    private Integer status;
    private Integer level;
    private java.util.Date recievetime;
    private Integer isfocus;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String title, String summary, String content, Integer type, Integer status, Integer level, java.util.Date recievetime, Integer isfocus) {
        this.id = id;
        this.title = title;
        this.summary = summary;
        this.content = content;
        this.type = type;
        this.status = status;
        this.level = level;
        this.recievetime = recievetime;
        this.isfocus = isfocus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public java.util.Date getRecievetime() {
        return recievetime;
    }

    public void setRecievetime(java.util.Date recievetime) {
        this.recievetime = recievetime;
    }

    public Integer getIsfocus() {
        return isfocus;
    }

    public void setIsfocus(Integer isfocus) {
        this.isfocus = isfocus;
    }

}
